# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-23 21:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('appcoin', '0002_auto_20161220_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataDump',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=255)),
                ('rank', models.IntegerField()),
                ('price_usd', models.DecimalField(decimal_places=10, max_digits=19)),
                ('price_btc', models.DecimalField(decimal_places=10, max_digits=19)),
                ('volume_usd', models.FloatField()),
                ('market_cap_usd', models.FloatField()),
                ('available_supply', models.FloatField()),
                ('total_supply', models.FloatField()),
                ('percent_change_1h', models.FloatField()),
                ('percent_change_24h', models.FloatField()),
                ('percent_change_7d', models.FloatField()),
                ('last_updated', models.DateTimeField()),
            ],
            managers=[
                ('DDManager', django.db.models.manager.Manager()),
            ],
        ),
    ]
